title: Walmart Cashback Pro
baseurl: "/walmart-cashback-pro"
url: "https://gategith.github.io"
include: [".nojekyll"]

plugins:
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: default

redirects:
  /verify: /walmart-cashback-pro/verify/
